/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useMemo, useState } from 'react';
import { useApp } from '../context/AppContext';
import {
  City,
  Festival,
  MasterSweet,
  SaleCenter,
  DiscountCoupon
} from '../types';
import {
  Database,
  Candy,
  Building2,
  Store,
  CalendarDays,
  Ticket,
  Plus,
  Save,
  CheckCircle2,
  AlertCircle,
  LogOut,
  ArrowLeft
} from 'lucide-react';

/* ------------------------------------------------------------------ *
 * Field configuration types                                          *
 * ------------------------------------------------------------------ */
type FieldType = 'text' | 'number' | 'boolean' | 'select' | 'textarea' | 'json';

interface FieldDef {
  name: string;
  label: string;
  type: FieldType;
  options?: { value: string; label: string }[];
  placeholder?: string;
  required?: boolean;
  /** Field cannot be edited once the record exists (e.g. primary keys). */
  lockOnEdit?: boolean;
  /** Field is managed automatically and hidden from the form entirely. */
  auto?: boolean;
  full?: boolean; // span full width in the grid
}

interface EntityConfig {
  key: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  records: any[];
  idOf: (r: any) => string;
  labelOf: (r: any) => string;
  /** id is generated by the create action, so it is not required on new. */
  autoId: boolean;
  empty: Record<string, any>;
  fields: FieldDef[];
  save: (data: Record<string, any>, isNew: boolean) => Promise<void>;
}

/* ------------------------------------------------------------------ *
 * Value coercion: form strings -> typed record                        *
 * ------------------------------------------------------------------ */
interface CoerceResult {
  ok: boolean;
  value: Record<string, any>;
  error?: string;
}

function coerceRecord(fields: FieldDef[], form: Record<string, any>): CoerceResult {
  const out: Record<string, any> = {};
  for (const f of fields) {
    const raw = form[f.name];

    if (f.type === 'number') {
      if (raw === '' || raw === undefined || raw === null) {
        out[f.name] = undefined;
      } else {
        const n = Number(raw);
        if (Number.isNaN(n)) return { ok: false, value: {}, error: `${f.label} must be a number` };
        out[f.name] = n;
      }
    } else if (f.type === 'boolean') {
      out[f.name] = Boolean(raw);
    } else if (f.type === 'json') {
      if (raw === '' || raw === undefined || raw === null) {
        out[f.name] = undefined;
      } else if (typeof raw === 'string') {
        try {
          out[f.name] = JSON.parse(raw);
        } catch {
          return { ok: false, value: {}, error: `${f.label} contains invalid JSON` };
        }
      } else {
        out[f.name] = raw;
      }
    } else {
      out[f.name] = raw === undefined || raw === null ? '' : String(raw);
    }

    if (f.required && (out[f.name] === undefined || out[f.name] === '')) {
      return { ok: false, value: {}, error: `${f.label} is required` };
    }
  }
  return { ok: true, value: out };
}

/** Prepare a record for editing: JSON fields become pretty strings. */
function toFormState(fields: FieldDef[], record: Record<string, any>): Record<string, any> {
  const out: Record<string, any> = {};
  for (const f of fields) {
    const v = record[f.name];
    if (f.type === 'json') {
      out[f.name] = v === undefined || v === null ? '' : JSON.stringify(v, null, 2);
    } else if (f.type === 'boolean') {
      out[f.name] = Boolean(v);
    } else {
      out[f.name] = v === undefined || v === null ? '' : v;
    }
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * The Admin Records Console                                          *
 * ------------------------------------------------------------------ */
export const AdminDashboardView: React.FC = () => {
  const {
    currentUser,
    logoutUser,
    setRole,
    cities,
    masterSweets,
    festivals,
    saleCenters,
    discounts,
    addMasterSweet,
    updateMasterSweet,
    addCity,
    updateCity,
    addFestival,
    updateFestival,
    createSaleCenter,
    updateSaleCenter,
    createDiscount,
    updateDiscount
  } = useApp();

  const cityOptions = useMemo(
    () => cities.map((c) => ({ value: c.id, label: `${c.nameEn} (${c.id})` })),
    [cities]
  );

  const entities: EntityConfig[] = useMemo(() => {
    return [
      /* ---------------- Master Sweets ---------------- */
      {
        key: 'sweets',
        label: 'Master Sweets',
        icon: Candy,
        records: masterSweets,
        idOf: (r: MasterSweet) => r.id,
        labelOf: (r: MasterSweet) => `${r.nameEn} — ${r.nameHi}`,
        autoId: false,
        empty: {
          id: '',
          nameHi: '',
          nameEn: '',
          category: 'traditional',
          hsnCode: '2106',
          gstPercent: 5,
          descriptionHi: '',
          descriptionEn: '',
          imageUrl: '',
          images: '',
          basePrice: '',
          discountPercent: '',
          shelfLifeDays: '',
          packSizeInfo: '',
          variants: '[\n  { "label": "1 kg (एक किलो)", "weightInKg": 1, "price": 700 }\n]',
          isPureVeg: true,
          ingredientsHi: ''
        },
        fields: [
          { name: 'id', label: 'ID', type: 'text', required: true, lockOnEdit: true },
          { name: 'nameHi', label: 'Name (Hindi)', type: 'text', required: true },
          { name: 'nameEn', label: 'Name (English)', type: 'text', required: true },
          {
            name: 'category',
            label: 'Category',
            type: 'select',
            options: [
              { value: 'dry', label: 'Dry' },
              { value: 'bengali', label: 'Bengali' },
              { value: 'traditional', label: 'Traditional' },
              { value: 'gift', label: 'Gift' },
              { value: 'mawa', label: 'Mawa' }
            ],
            required: true
          },
          { name: 'hsnCode', label: 'HSN Code', type: 'text', required: true },
          { name: 'gstPercent', label: 'GST %', type: 'number', required: true },
          { name: 'basePrice', label: 'Base Price (₹/kg)', type: 'number' },
          { name: 'discountPercent', label: 'Discount %', type: 'number' },
          { name: 'shelfLifeDays', label: 'Shelf Life (days)', type: 'number' },
          { name: 'isPureVeg', label: 'Pure Veg', type: 'boolean' },
          { name: 'imageUrl', label: 'Primary Image URL', type: 'text', required: true, full: true },
          { name: 'packSizeInfo', label: 'Pack Size Info', type: 'text', full: true },
          { name: 'descriptionHi', label: 'Description (Hindi)', type: 'textarea', required: true, full: true },
          { name: 'descriptionEn', label: 'Description (English)', type: 'textarea', required: true, full: true },
          { name: 'ingredientsHi', label: 'Ingredients (Hindi)', type: 'text', full: true },
          { name: 'images', label: 'Images (JSON array of URLs)', type: 'json', full: true },
          { name: 'variants', label: 'Variants (JSON array)', type: 'json', required: true, full: true }
        ],
        save: async (data, isNew) => {
          const sweet = data as MasterSweet;
          if (!sweet.images) sweet.images = [sweet.imageUrl];
          if (isNew) await addMasterSweet(sweet);
          else await updateMasterSweet(sweet);
        }
      },

      /* ---------------- Cities ---------------- */
      {
        key: 'cities',
        label: 'Cities',
        icon: Building2,
        records: cities,
        idOf: (r: City) => r.id,
        labelOf: (r: City) => `${r.nameEn} (${r.id})`,
        autoId: false,
        empty: {
          id: '',
          nameHi: '',
          nameEn: '',
          stateHi: 'राजस्थान',
          stateEn: 'Rajasthan',
          districtHi: '',
          adminName: '',
          adminPhone: '',
          isActive: true,
          sweets: '[]'
        },
        fields: [
          { name: 'id', label: 'ID', type: 'text', required: true, lockOnEdit: true },
          { name: 'nameHi', label: 'Name (Hindi)', type: 'text', required: true },
          { name: 'nameEn', label: 'Name (English)', type: 'text', required: true },
          { name: 'stateHi', label: 'State (Hindi)', type: 'text', required: true },
          { name: 'stateEn', label: 'State (English)', type: 'text', required: true },
          { name: 'districtHi', label: 'District (Hindi)', type: 'text', required: true },
          { name: 'adminName', label: 'Admin Name', type: 'text', required: true },
          { name: 'adminPhone', label: 'Admin Phone', type: 'text', required: true },
          { name: 'isActive', label: 'Active', type: 'boolean' },
          { name: 'sweets', label: 'City Sweets (JSON array)', type: 'json', required: true, full: true }
        ],
        save: async (data, isNew) => {
          const city = data as City;
          if (isNew) await addCity(city);
          else await updateCity(city);
        }
      },

      /* ---------------- Festivals ---------------- */
      {
        key: 'festivals',
        label: 'Festivals',
        icon: CalendarDays,
        records: festivals,
        idOf: (r: Festival) => r.id,
        labelOf: (r: Festival) => `${r.nameEn} (${r.status})`,
        autoId: false,
        empty: {
          id: '',
          nameHi: '',
          nameEn: '',
          status: 'draft',
          startDate: '',
          cutoffDate: '',
          distributionStartDate: '',
          distributionEndDate: '',
          maxKgPerBooking: 10,
          defaultMitraCreditLimit: 25000
        },
        fields: [
          { name: 'id', label: 'ID', type: 'text', required: true, lockOnEdit: true },
          { name: 'nameHi', label: 'Name (Hindi)', type: 'text', required: true },
          { name: 'nameEn', label: 'Name (English)', type: 'text', required: true },
          {
            name: 'status',
            label: 'Status',
            type: 'select',
            options: [
              { value: 'active', label: 'Active' },
              { value: 'draft', label: 'Draft' },
              { value: 'completed', label: 'Completed' }
            ],
            required: true
          },
          { name: 'startDate', label: 'Start Date (YYYY-MM-DD)', type: 'text', required: true },
          { name: 'cutoffDate', label: 'Cutoff Date (YYYY-MM-DD)', type: 'text', required: true },
          { name: 'distributionStartDate', label: 'Distribution Start', type: 'text', required: true },
          { name: 'distributionEndDate', label: 'Distribution End', type: 'text', required: true },
          { name: 'maxKgPerBooking', label: 'Max Kg / Booking', type: 'number', required: true },
          { name: 'defaultMitraCreditLimit', label: 'Default Mitra Credit Limit (₹)', type: 'number', required: true }
        ],
        save: async (data, isNew) => {
          const fest = data as Festival;
          if (isNew) await addFestival(fest);
          else await updateFestival(fest.id, fest);
        }
      },

      /* ---------------- Sale Centers ---------------- */
      {
        key: 'centers',
        label: 'Sale Centers',
        icon: Store,
        records: saleCenters,
        idOf: (r: SaleCenter) => r.id,
        labelOf: (r: SaleCenter) => `${r.nameEn} — ${r.cityId}`,
        autoId: true,
        empty: {
          id: '',
          cityId: cities[0]?.id || '',
          nameHi: '',
          nameEn: '',
          type: 'standalone',
          ownerName: '',
          ownerPhone: '',
          ownerEmail: '',
          addressHi: '',
          addressEn: '',
          pincode: '',
          timing: '09:00 AM - 08:00 PM',
          mapUrl: '',
          isActive: true,
          gstin: ''
        },
        fields: [
          { name: 'id', label: 'ID (auto for new)', type: 'text', lockOnEdit: true },
          { name: 'cityId', label: 'City', type: 'select', options: cityOptions, required: true },
          {
            name: 'type',
            label: 'Type',
            type: 'select',
            options: [
              { value: 'standalone', label: 'Standalone' },
              { value: 'mitra_kendra', label: 'Mitra Kendra' }
            ],
            required: true
          },
          { name: 'nameHi', label: 'Name (Hindi)', type: 'text', required: true },
          { name: 'nameEn', label: 'Name (English)', type: 'text', required: true },
          { name: 'ownerName', label: 'Owner Name', type: 'text', required: true },
          { name: 'ownerPhone', label: 'Owner Phone', type: 'text', required: true },
          { name: 'ownerEmail', label: 'Owner Email', type: 'text', required: true },
          { name: 'pincode', label: 'Pincode', type: 'text', required: true },
          { name: 'timing', label: 'Timing', type: 'text', required: true },
          { name: 'gstin', label: 'GSTIN', type: 'text' },
          { name: 'isActive', label: 'Active', type: 'boolean' },
          { name: 'addressHi', label: 'Address (Hindi)', type: 'textarea', required: true, full: true },
          { name: 'addressEn', label: 'Address (English)', type: 'textarea', required: true, full: true },
          { name: 'mapUrl', label: 'Map URL', type: 'text', full: true }
        ],
        save: async (data, isNew) => {
          if (isNew) {
            const { id, ...rest } = data;
            await createSaleCenter(rest as Omit<SaleCenter, 'id'>);
          } else {
            await updateSaleCenter(data as SaleCenter);
          }
        }
      },

      /* ---------------- Discounts ---------------- */
      {
        key: 'discounts',
        label: 'Discounts',
        icon: Ticket,
        records: discounts,
        idOf: (r: DiscountCoupon) => r.id,
        labelOf: (r: DiscountCoupon) => `${r.code} (${r.cityId})`,
        autoId: true,
        empty: {
          id: '',
          code: '',
          titleHi: '',
          titleEn: '',
          descriptionHi: '',
          cityId: 'all',
          centerId: 'all',
          discountType: 'flat',
          discountValue: 50,
          minOrderAmount: 0,
          maxDiscountAmount: '',
          startDate: '',
          expiryDate: '',
          usageLimit: '',
          isActive: true
        },
        fields: [
          { name: 'id', label: 'ID (auto for new)', type: 'text', lockOnEdit: true },
          { name: 'code', label: 'Coupon Code', type: 'text', required: true },
          {
            name: 'cityId',
            label: 'City',
            type: 'select',
            options: [{ value: 'all', label: 'All Cities' }, ...cityOptions],
            required: true
          },
          { name: 'centerId', label: "Center ID ('all' or specific)", type: 'text' },
          {
            name: 'discountType',
            label: 'Discount Type',
            type: 'select',
            options: [
              { value: 'flat', label: 'Flat (₹)' },
              { value: 'percentage', label: 'Percentage (%)' }
            ],
            required: true
          },
          { name: 'discountValue', label: 'Discount Value', type: 'number', required: true },
          { name: 'minOrderAmount', label: 'Min Order Amount (₹)', type: 'number', required: true },
          { name: 'maxDiscountAmount', label: 'Max Discount Cap (₹)', type: 'number' },
          { name: 'usageLimit', label: 'Usage Limit', type: 'number' },
          { name: 'startDate', label: 'Start Date (YYYY-MM-DD)', type: 'text' },
          { name: 'expiryDate', label: 'Expiry Date (YYYY-MM-DD)', type: 'text' },
          { name: 'isActive', label: 'Active', type: 'boolean' },
          { name: 'titleHi', label: 'Title (Hindi)', type: 'text', required: true, full: true },
          { name: 'titleEn', label: 'Title (English)', type: 'text', required: true, full: true },
          { name: 'descriptionHi', label: 'Description (Hindi)', type: 'textarea', full: true }
        ],
        save: async (data, isNew) => {
          if (isNew) {
            const { id, ...rest } = data;
            await createDiscount(rest as Omit<DiscountCoupon, 'id' | 'createdAt' | 'timesUsed'>);
          } else {
            const { id, ...updates } = data;
            await updateDiscount(id, updates as Partial<DiscountCoupon>);
          }
        }
      }
    ];
  }, [
    cities,
    masterSweets,
    festivals,
    saleCenters,
    discounts,
    cityOptions,
    addMasterSweet,
    updateMasterSweet,
    addCity,
    updateCity,
    addFestival,
    updateFestival,
    createSaleCenter,
    updateSaleCenter,
    createDiscount,
    updateDiscount
  ]);

  const [activeKey, setActiveKey] = useState(entities[0].key);
  const [selectedId, setSelectedId] = useState('new'); // 'new' or a record id
  const [form, setForm] = useState<Record<string, any>>(() => toFormState(entities[0].fields, entities[0].empty));
  const [status, setStatus] = useState<{ type: 'ok' | 'err'; msg: string } | null>(null);
  const [saving, setSaving] = useState(false);

  const activeEntity = entities.find((e) => e.key === activeKey) || entities[0];

  const switchEntity = (key: string) => {
    const ent = entities.find((e) => e.key === key)!;
    setActiveKey(key);
    setSelectedId('new');
    setForm(toFormState(ent.fields, ent.empty));
    setStatus(null);
  };

  const switchRecord = (id: string) => {
    setSelectedId(id);
    setStatus(null);
    if (id === 'new') {
      setForm(toFormState(activeEntity.fields, activeEntity.empty));
    } else {
      const rec = activeEntity.records.find((r) => activeEntity.idOf(r) === id);
      setForm(toFormState(activeEntity.fields, rec || activeEntity.empty));
    }
  };

  const setField = (name: string, value: any) => {
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const isNew = selectedId === 'new';

  const handleSave = async () => {
    setStatus(null);
    const coerced = coerceRecord(activeEntity.fields, form);
    if (!coerced.ok) {
      setStatus({ type: 'err', msg: coerced.error || 'Invalid input' });
      return;
    }
    // Drop undefined keys so we don't overwrite with nulls unintentionally.
    const clean: Record<string, any> = {};
    Object.entries(coerced.value).forEach(([k, v]) => {
      if (v !== undefined) clean[k] = v;
    });

    setSaving(true);
    try {
      await activeEntity.save(clean, isNew);
      setStatus({
        type: 'ok',
        msg: isNew ? `${activeEntity.label} record created successfully.` : `${activeEntity.label} record updated successfully.`
      });
      if (isNew) {
        setForm(toFormState(activeEntity.fields, activeEntity.empty));
      }
    } catch (e: any) {
      setStatus({ type: 'err', msg: e?.message || 'Save failed. Check the console for details.' });
    } finally {
      setSaving(false);
    }
  };

  const visibleFields = activeEntity.fields.filter((f) => !f.auto);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      {/* Top bar */}
      <header className="bg-slate-900 border-b border-slate-800 sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="p-2 bg-amber-400 text-slate-950 rounded-xl shrink-0">
              <Database className="w-5 h-5" />
            </div>
            <div className="min-w-0">
              <h1 className="font-black text-base sm:text-lg leading-tight truncate">Records Admin Console</h1>
              <p className="text-[11px] text-slate-400 truncate">
                Super Admin · {currentUser?.name || 'admin'}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={() => {
                if (typeof window !== 'undefined') window.location.hash = '';
                setRole('super_admin');
              }}
              className="text-xs font-bold bg-slate-800 hover:bg-slate-700 border border-slate-600 px-3 py-2 rounded-xl flex items-center gap-1.5 cursor-pointer"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Admin Home</span>
            </button>
            <button
              onClick={() => {
                logoutUser();
                if (typeof window !== 'undefined') window.location.hash = '';
              }}
              className="text-xs font-bold bg-rose-600 hover:bg-rose-500 px-3 py-2 rounded-xl flex items-center gap-1.5 cursor-pointer"
            >
              <LogOut className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Logout</span>
            </button>
          </div>
        </div>

        {/* Entity tabs */}
        <div className="max-w-6xl mx-auto px-4 pb-3 flex gap-1.5 overflow-x-auto">
          {entities.map((e) => {
            const Icon = e.icon;
            const active = e.key === activeKey;
            return (
              <button
                key={e.key}
                onClick={() => switchEntity(e.key)}
                className={`px-3 py-2 rounded-xl text-xs font-bold whitespace-nowrap flex items-center gap-1.5 cursor-pointer transition-colors ${
                  active
                    ? 'bg-amber-400 text-slate-950'
                    : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                {e.label}
                <span className={`ml-1 px-1.5 rounded-full text-[10px] ${active ? 'bg-slate-950/20' : 'bg-slate-950/40'}`}>
                  {e.records.length}
                </span>
              </button>
            );
          })}
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-5 space-y-4">
        {/* Record selector */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 flex flex-col sm:flex-row sm:items-center gap-3">
          <label className="text-xs font-bold text-slate-400 uppercase tracking-wide">
            {activeEntity.label} record
          </label>
          <select
            value={selectedId}
            onChange={(e) => switchRecord(e.target.value)}
            className="flex-1 bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-sm focus:outline-none focus:border-amber-400"
          >
            <option value="new">➕ New record…</option>
            {activeEntity.records.map((r) => (
              <option key={activeEntity.idOf(r)} value={activeEntity.idOf(r)}>
                {activeEntity.labelOf(r)}
              </option>
            ))}
          </select>
          <span
            className={`text-[11px] font-bold px-2.5 py-1 rounded-lg self-start sm:self-auto ${
              isNew ? 'bg-emerald-500/20 text-emerald-300' : 'bg-blue-500/20 text-blue-300'
            }`}
          >
            {isNew ? 'CREATE' : 'EDIT'}
          </span>
        </div>

        {/* Status banner */}
        {status && (
          <div
            className={`rounded-xl px-4 py-3 text-sm flex items-center gap-2 ${
              status.type === 'ok'
                ? 'bg-emerald-950/60 border border-emerald-500/40 text-emerald-200'
                : 'bg-rose-950/60 border border-rose-500/40 text-rose-200'
            }`}
          >
            {status.type === 'ok' ? (
              <CheckCircle2 className="w-4 h-4 shrink-0" />
            ) : (
              <AlertCircle className="w-4 h-4 shrink-0" />
            )}
            <span>{status.msg}</span>
          </div>
        )}

        {/* Form */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {visibleFields.map((f) => {
              const locked = !isNew && f.lockOnEdit;
              const value = form[f.name];
              return (
                <div key={f.name} className={f.full || f.type === 'json' || f.type === 'textarea' ? 'sm:col-span-2' : ''}>
                  <label className="text-xs font-bold text-slate-300 flex items-center gap-1 mb-1">
                    {f.label}
                    {f.required && <span className="text-rose-400">*</span>}
                    {locked && <span className="text-slate-500 font-normal">(locked)</span>}
                  </label>

                  {f.type === 'boolean' ? (
                    <label className="inline-flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={Boolean(value)}
                        onChange={(e) => setField(f.name, e.target.checked)}
                        className="w-4 h-4 accent-amber-400"
                      />
                      <span className="text-sm text-slate-300">{value ? 'Yes' : 'No'}</span>
                    </label>
                  ) : f.type === 'select' ? (
                    <select
                      value={value ?? ''}
                      disabled={locked}
                      onChange={(e) => setField(f.name, e.target.value)}
                      className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-sm focus:outline-none focus:border-amber-400 disabled:opacity-50"
                    >
                      {(f.options || []).map((o) => (
                        <option key={o.value} value={o.value}>
                          {o.label}
                        </option>
                      ))}
                    </select>
                  ) : f.type === 'textarea' ? (
                    <textarea
                      value={value ?? ''}
                      disabled={locked}
                      rows={2}
                      placeholder={f.placeholder}
                      onChange={(e) => setField(f.name, e.target.value)}
                      className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-sm focus:outline-none focus:border-amber-400 disabled:opacity-50"
                    />
                  ) : f.type === 'json' ? (
                    <textarea
                      value={value ?? ''}
                      disabled={locked}
                      rows={6}
                      spellCheck={false}
                      placeholder={f.placeholder}
                      onChange={(e) => setField(f.name, e.target.value)}
                      className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs font-mono text-emerald-200 focus:outline-none focus:border-amber-400 disabled:opacity-50"
                    />
                  ) : (
                    <input
                      type={f.type === 'number' ? 'number' : 'text'}
                      value={value ?? ''}
                      disabled={locked}
                      placeholder={f.placeholder}
                      onChange={(e) => setField(f.name, e.target.value)}
                      className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-sm focus:outline-none focus:border-amber-400 disabled:opacity-50"
                    />
                  )}
                </div>
              );
            })}
          </div>

          <div className="mt-5 flex items-center gap-3">
            <button
              onClick={handleSave}
              disabled={saving}
              className="bg-amber-400 hover:bg-amber-300 text-slate-950 font-black text-sm px-5 py-2.5 rounded-xl flex items-center gap-2 cursor-pointer disabled:opacity-60"
            >
              {isNew ? <Plus className="w-4 h-4" /> : <Save className="w-4 h-4" />}
              {saving ? 'Saving…' : isNew ? 'Create Record' : 'Save Changes'}
            </button>
            {!isNew && (
              <button
                onClick={() => switchRecord('new')}
                className="text-xs font-bold bg-slate-800 hover:bg-slate-700 border border-slate-600 px-4 py-2.5 rounded-xl cursor-pointer"
              >
                Cancel / New
              </button>
            )}
          </div>
        </div>

        <p className="text-[11px] text-slate-500 leading-relaxed">
          JSON fields (variants, images, city sweets) must be valid JSON. Locked fields such as primary IDs cannot be
          changed after a record is created. Changes are written to the database through the same API the rest of the app
          uses.
        </p>
      </main>
    </div>
  );
};
