/**
 * ID generation utilities for Sahakar Bharati.
 * 
 * Generates unique, cryptographically secure IDs for use throughout the application.
 * Used for invoices, bookings, transactions, and other entities.
 */

import { randomBytes } from 'crypto';

/**
 * Generate a unique ID using crypto.randomBytes.
 * Format: timestamp (ms) + random hex string, optionally with prefix
 * Example: 1727814000000_a3f9e2c1b5d7 or inv_1727814000000_a3f9e2c1b5d7
 * 
 * This provides both temporal ordering and randomness for uniqueness.
 * 
 * @param prefix - Optional prefix (e.g., "inv", "bk", "log")
 * @returns Unique ID, optionally prefixed
 */
export function genId(prefix?: string): string {
  const timestamp = Date.now();
  const randomPart = randomBytes(6).toString('hex');
  const id = `${timestamp}_${randomPart}`;
  return prefix ? `${prefix}_${id}` : id;
}

/**
 * Generate a prefixed ID (e.g., "inv_" for invoices, "bk_" for bookings).
 * Useful for database sharding and identifying entity type from ID.
 * 
 * @param prefix - Prefix for the ID (e.g., "inv", "bk", "tx")
 * @returns Prefixed ID (e.g., "inv_1727814000000_a3f9e2c1b5d7")
 */
export function genIdWithPrefix(prefix: string): string {
  const id = genId();
  return `${prefix}_${id}`;
}

/**
 * Generate a nanoid-style ID (alphanumeric, 12 characters).
 * Shorter and more URL-friendly than full genId().
 * Collision probability is still very low (~1 in 10^20 for 10M IDs).
 * 
 * @returns 12-character alphanumeric ID
 */
export function genShortId(): string {
  const alphabet = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  let id = '';
  const bytes = randomBytes(12);
  for (let i = 0; i < 12; i++) {
    id += alphabet[bytes[i] % alphabet.length];
  }
  return id;
}

/**
 * Validate an ID generated by genId().
 * Checks format: timestamp_hex
 * 
 * @param id - ID to validate
 * @returns true if valid format, false otherwise
 */
export function isValidId(id: string): boolean {
  const match = /^\d+_[a-f0-9]{12}$/.test(id);
  return match;
}
